[build]
  base = "mi-app/frontend"
  publish = "dist"
  command = "npm install --include=optional && npm run build"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200